version: '3.8'
services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

#   timetracking-bot:
#     container_name: timetracking-bot.local
#     build:
#       context: .
#     environment:
#       - TIMETRACKING_TG_TOKEN=${TIMETRACKING_TG_TOKEN}
#     volumes:
#       - timetracking-data:/app/data/
#     restart: always

# volumes:
#   timetracking-data:
